from gtts import gTTS

# Your script
script = "In the colorful city of Dhaka, Bangladesh, there lived a man named Farhan who had a rather peculiar talent. Every time he let out his hearty laughter, it seemed like a chain reaction of giggles and grins spread through the entire neighborhood. People loved being around him as his laughter could brighten the dullest of days.Farhan dreamed of becoming a stand-up comedian, and he believed his unique gift would pave the way for success. So, one evening, he gathered his courage and decided to perform at the local comedy club.As he took the stage, a hushed anticipation filled the room. Farhan took a deep breath and began his act. But to his surprise, instead of laughter, there was an awkward silence. His jokes seemed to fall flat, and he couldn't find the right comedic timing.Feeling disheartened, Farhan left the stage, determined to improve his skills. He spent hours and days practicing, studying comedy greats, and refining his performance. However, every time he returned to the club, the response remained lackluster.But the people of Dhaka were not ones to give up easily on their dreamers. They had seen the magic of Farhan's laughter before and knew he had something special. So, they decided to organize a Hasya Utsab (Laughter Festival) in the heart of Dhaka, with the sole aim of helping Farhan find his comedic voice.On the eventful night of the Hasya Utsab, the venue was filled with laughter enthusiasts from all corners of the city. Farhan, a bit nervous but hopeful, stepped onto the stage once again. This time, he decided to take a different approach. Instead of telling traditional jokes, he shared humorous tales and funny incidents from his own life, letting his infectious laughter lead the way.As Farhan laughed heartily, the audience couldn't resist joining in, and a wave of laughter filled the entire venue. Farhan's laughter became the catalyst for a joyous uproar, and the atmosphere was electrifying. The crowd roared with laughter, and the Hasya Utsab became a resounding success. From that moment on, Farhan's stand-up comedy career soared to new heights. His unique style and infectious laughter made him a beloved sensation not only in Dhaka but across Bangladesh. He performed in bigger venues, appeared on television shows, and became a household name.In the end, it was Farhan's ability to find humor in everyday life and his contagious laughter that brought him success. He had proven that sometimes, the most unique path to success is the one that makes everyone laugh together. And in Dhaka, laughter was the language of happiness, and Farhan was the king of laughter, spreading joy wherever he went."

# Language in which you want to convert
language = 'en'

# Create a gTTS object
tts = gTTS(text=script, lang=language, slow=False)

# Save the audio file
tts.save('output.mp3')
